workflows:
    android-workflow-id:
        name: Android Sample Workflow
        environment:
            flutter: stable

        publishing:
          email:
            recipients:
              - nguiranedev120@gmail.com
            notify:
              success: true
              failure: true