// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq67-vrNxE_T4Lx_lYJuwV94W0nCG4Xj4',
    appId: '1:926343745991:web:9ab34bfa98e4728e8749e2',
    messagingSenderId: '926343745991',
    projectId: 'gestionstock-32189',
    authDomain: 'gestionstock-32189.firebaseapp.com',
    storageBucket: 'gestionstock-32189.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmhRVbtXkD23vI1UydybArTg1bYgInofE',
    appId: '1:926343745991:android:11a3441c7db1606b8749e2',
    messagingSenderId: '926343745991',
    projectId: 'gestionstock-32189',
    storageBucket: 'gestionstock-32189.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2QDnRsi7qxBk03m8aQjt6YTsSmrTCqq4',
    appId: '1:926343745991:ios:fe4c9e588cb562bb8749e2',
    messagingSenderId: '926343745991',
    projectId: 'gestionstock-32189',
    storageBucket: 'gestionstock-32189.appspot.com',
    iosBundleId: 'com.example.gestionstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2QDnRsi7qxBk03m8aQjt6YTsSmrTCqq4',
    appId: '1:926343745991:ios:fe4c9e588cb562bb8749e2',
    messagingSenderId: '926343745991',
    projectId: 'gestionstock-32189',
    storageBucket: 'gestionstock-32189.appspot.com',
    iosBundleId: 'com.example.gestionstock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq67-vrNxE_T4Lx_lYJuwV94W0nCG4Xj4',
    appId: '1:926343745991:web:c60225708a944b648749e2',
    messagingSenderId: '926343745991',
    projectId: 'gestionstock-32189',
    authDomain: 'gestionstock-32189.firebaseapp.com',
    storageBucket: 'gestionstock-32189.appspot.com',
  );
}
